CREATE TABLE DEPARTMENTS (
	ID serial PRIMARY KEY, 
	NAME VARCHAR (100) NOT NULL
);

CREATE TABLE EMPLOYEES (
	ID serial PRIMARY KEY, 
	NAME VARCHAR (50) NOT NULL, 
	SALARY INTEGER, 
	DEPARTMENT_ID INT REFERENCES DEPARTMENTS(ID)
);


INSERT INTO DEPARTMENTS (NAME) VALUES ('IT');
INSERT INTO DEPARTMENTS (NAME) VALUES ('Sales');

INSERT INTO EMPLOYEES (NAME, SALARY, DEPARTMENT_ID) VALUES ('Joe', 85000, 1);
INSERT INTO EMPLOYEES (NAME, SALARY, DEPARTMENT_ID) VALUES ('Henry', 80000, 2);
INSERT INTO EMPLOYEES (NAME, SALARY, DEPARTMENT_ID) VALUES ('Sam', 60000, 2);
INSERT INTO EMPLOYEES (NAME, SALARY, DEPARTMENT_ID) VALUES ('Max', 90000, 1);
INSERT INTO EMPLOYEES (NAME, SALARY, DEPARTMENT_ID) VALUES ('Janet', 69000, 1);
INSERT INTO EMPLOYEES (NAME, SALARY, DEPARTMENT_ID) VALUES ('Randy', 85000, 1);
INSERT INTO EMPLOYEES (NAME, SALARY, DEPARTMENT_ID) VALUES ('Will', 70000, 1);


SELECT 
    DEPARTMENTS.NAME,
	EMP.NAME,
	EMP.SALARY
FROM
	(SELECT *, 
	 	RANK() OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC) 
	 		AS EARNING_RANK FROM EMPLOYEES) AS EMP
JOIN DEPARTMENTS ON EMP.DEPARTMENT_ID = DEPARTMENTS.ID
WHERE EARNING_RANK < 5;